spring:
  # CONSOLE 관련 세팅
  output:
    ansi:
      enabled: always
  thymeleaf:
    cache: false # 타임리프 캐시 끄기
    prefix: file:src/main/resources/templates/ # 타임리프 캐시 끄기(이 설정을 해야 꺼짐)
    devtools:
      enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3306/qna_service?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: 0000
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 옵션 none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
